### ISSUE TITLE
Apply button request

### ISSUE THREAD

**Issue by MrAdrianPl** [jayanam/jcurve-tools#1]
Hi it would be great to have an apply button in the n panel gui any chances that you'll implement such thing?

**Comment by jayanam** [comment]
Ok, what should apply do?

**Comment by MrAdrianPl** [comment]
oh right ive meant to apply the modifier stack that is created whenever you click create button to make an array on the curve it would be a cool qol feature i think.

**Comment by jayanam** [comment]
* Apply is added
* Bugfix: Added object is moved now to location of the curve
* Remove button is removed, because you can remove the added object as well, so not needed.

![image](https://user-images.githubusercontent.com/18039584/162585902-24efa9fb-d2d8-4423-8621-ddaf689aa24f.png)
